name: "Compile Stream Deck Plugin"
description: "This action compiles a Stream Deck Plugins source to a .streamDeckPlugin file"
author: "@AlexHaible"
branding:
  icon: check
  color: purple
inputs:
  input-directory:
    description: "Where is your code?"
    required: true
  output-directory:
    description: "Where you want the .streamDeckPlugin?"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate .streamDeckPlugin
      run: ${{ github.action_path }}/tools/mac/DistributionTool -b -i ${{ github.workspace }}${{ inputs.input-directory }} -o ${{ github.workspace }}${{ inputs.output-directory }}
      shell: bash
